### ISSUE TITLE
reviver fails when used with a page that uses CSP policies

### ISSUE THREAD

**Issue by johnhunter** [storybookjs/telejson#18]
When Storybook is hosted in an environment using [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) policies `reviver` fails the following error:

> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

https://github.com/storybookjs/telejson/blob/0a6e9748d64a90f6b16ecd6e6b0c3e4b1f6046b1/src/index.js#L215

I'm not sure if this is resolvable. It might be worth mentioning it in Storybook docs in the meantime.

**Comment by ndelangen** [comment]
I can wrap it with a try-catch, so it doesn't break?

**Comment by johnhunter** [comment]
Hi, thanks for looking into this.

It might reduce the noise in the console but I don't think it will solve the issue.  The CSP policy prevents the the browser from constructing a function from a string, and that undermines the whole  idea of serialising functions through messages. I don't think there is an alternative to using some sort of eval when passing functions in messages.

For us the solution was to turn off the 'unsafe-eval' CSP rule. AFAIK the Storybook architecture depends on message passing for functions so we have accepted this as a requirement of hosting a Storybook instance.

**Comment by ndelangen** [comment]
It only depends on that for a very select set of features, so if you're not using those it should be ok to ignore it.

**Comment by johnhunter** [comment]
Aha. Good to know!

I haven't confirmed it but it looks like a `try-catch` would handle the error: https://stackoverflow.com/a/42607885

Thanks.

**Comment by intuitivecat** [comment]
For us this is more than a console error, this is blocking us from deploying our StoryBook design system Docs into an origin service which has CSP restrictions on unsafe-eval, as the stories will not render.    If there is a way to build w/o reviver I have not found it.

**Comment by khanzzirfan** [comment]
Hi @johnhunter ,
Is there a way to fix this issue? In a banking domain we cannot host latest storybookV6 with blocking CSP policies in places. 
new Function and eval are both not allowed as per csp policies.

**Comment by johnhunter** [comment]
Hi @khanzzirfan I'm not sure, we modified our CSP policy as we only use Storybook internally.
