### ISSUE TITLE
Potential crypto-miner in package

### ISSUE THREAD

**Issue by AlexanderOttenhoff** [storybookjs/telejson#26]
I recently setup Storybook to test it out and encountered the error in the attached screenshot when calling action on a React Component. The last line in the stack trace before Metamask is called is: https://github.com/storybookjs/telejson/blob/master/src/index.ts#L318

![image](https://user-images.githubusercontent.com/4759404/67476672-c25de880-f658-11e9-9087-d0452c4c317c.png)

**Comment by shilman** [comment]
@AlexanderOttenhoff Do you have a reproduction?

**Comment by ndelangen** [comment]
Something that gets stringified is calling this I think, `inpage.js` isn't something from storybook OR telejson AFAIK.

@AlexanderOttenhoff could you please trace where `inpage.js` comes from and isolate what is being stringified?

**Comment by ndelangen** [comment]
@AlexanderOttenhoff Any news on this? I've investigated on my end, what it could be, and I have come up with nothing. Please if you have more information to give me, that could help...?
