### ISSUE TITLE
Performance enhancements

### ISSUE THREAD

**Issue by shilman** [storybookjs/telejson#42]
From a user's (private) storybook:

![](https://media.discordapp.net/attachments/735318499144105994/738794390696493137/Screen_Shot_2020-07-31_at_12.24.56_PM.png)

Line by line in parsing:

![](https://media.discordapp.net/attachments/735318499144105994/738795276034113536/Screen_Shot_2020-07-31_at_12.27.20_PM.png)

Looks like all the time is spent scanning the list (1s out of 8s total)

And here's another hot spot another (also 1s), also a list scan:

![](https://media.discordapp.net/attachments/735318499144105994/738797578606477354/Screen_Shot_2020-07-31_at_12.37.40_PM.png)

**Comment by shilman** [comment]
![image](https://user-images.githubusercontent.com/488689/89057977-125c9f00-d391-11ea-9c82-6d2af8440587.png)

stringify accounts for 63% of all script evaluation on the preview 🤦

**Comment by blaine-stripe** [comment]
#43 and #44 have gone a long way to improving the performance, but I believe that a bit more can be achieved by reorganizing the type checks to have the fast checks near the top (like string, number, undefined). I will submit a patch for this sometime today or tomorrow.

**Comment by ndelangen** [comment]
@shilman can we close this issue, or would you want to keep it open to track more perf improvements?
