### ISSUE TITLE
[Bug]  Can't resolve 'telejson'

### ISSUE THREAD

**Issue by lastIndexOf** [storybookjs/telejson#68]
![image](https://user-images.githubusercontent.com/13101975/118769758-15d6fd80-b8b3-11eb-85e9-e429087f7b88.png)

![image](https://user-images.githubusercontent.com/13101975/118769886-399a4380-b8b3-11eb-8edf-4e9fa68b7df9.png)

v5.3.1

**Comment by JounQin** [comment]
Did you try `v5.3.2`?

@ndelangen Should we remove or change the value of `module` property, it seems to be unnecessary anymore.

**Comment by ndelangen** [comment]
I've updated the package.json, sorry I messed this up.
