### ISSUE TITLE
`undefined` not supported

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/telejson#7]
See https://github.com/storybooks/storybook/issues/4487#issuecomment-485805825

```
parse(stringify({foo: undefined}))
> {}
```

**Comment by christophehurpeau** [comment]
This is the spec of JSON.stringify that removes undefined values, I can't see how we could fix this ?

**Comment by christophehurpeau** [comment]
https://www.ecma-international.org/ecma-262/5.1/#sec-15.12.2

> If it returns undefined then the property is deleted from the result.

**Comment by Hypnosphi** [comment]
>  I can't see how we could fix this

Avoid using JSON.parse?

**Comment by christophehurpeau** [comment]
Note that undefined is only not "supported" when it's a value in an object.
For example, the following works:
> telejson.parse(telejson.stringify([undefined]))
