### ISSUE TITLE
primitives should'n be deduplicated

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/telejson#8]
I have caught a weird bug in storybook when addons panel keeps getting hidden on each page reload. The probable reason is that I have this in my localStorage:

```
{
  ...
  layout: {
    isFullscreen: false
    isToolshown: true
    panelPosition: "bottom"
    showNav: "_duplicate_root.layout.isToolshown"
    showPanel: "_duplicate_root.layout.isFullscreen"
  }
}
```

There's no actual connection between `isFullscreen` and `showPanel` so they shouldn't link to each other

**Comment by ndelangen** [comment]
agreed, that's a bug
