### ISSUE TITLE
[Bug] License file?

### ISSUE THREAD

**Issue by edgan** [storybookjs/telejson#82]
### Describe the bug

I don't see any license file. Can one be decided on and added to the repository? Would a PR help?

Here is a quote from the license. It is generally interpreted as a copy of the license in the git repository, and in any downloaded copies of the code like from npm or yarn.

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

**Comment by phillyc** [comment]
Copyright info would be helpful as well. I want to give credit where credit is due!
